### ISSUE TITLE
Direct Messages?

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/forums-plugins#3]
Is there a method for one member to Direct Message another? Apparently this is used a lot in the SRM/Marathon Match group.

**Comment by jmgasper** [comment]
@rootelement - Yep, this is a thing.

![Screen Shot 2020-04-17 at 10 51 21](https://user-images.githubusercontent.com/21790/79520174-64efa500-8099-11ea-816a-090faf45caf6.png)

![Screen Shot 2020-04-17 at 10 51 12](https://user-images.githubusercontent.com/21790/79520177-6620d200-8099-11ea-9565-6d2e0004ceb6.png)
