### ISSUE TITLE
Override Vanilla Forums Profile

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/forums-plugins#4]
Can we override the Vanilla profile and link out to topcoder profile (custom plugin?)

- [ ] Clicking your avatar in the top right corner should take you to `topcoder.com/members/<handle>`

**Comment by jmgasper** [comment]
@rootelement - We *could* do this, but we would lose some of the profile ability in Vanilla.  Is that alright?

I think most things we can do without:

* `Edit Profile`
* `Change My Picture`
* `Access Tokens` (only available to admins anyways)
* `Quote Settings`

But, I think the `Notification Preferences` could be useful.  Maybe we can tweak the header to just have options to go to the Topcoder profile and show notification preferences and get rid of everything else?

![Screen Shot 2020-04-17 at 10 50 18](https://user-images.githubusercontent.com/21790/79520116-3bcf1480-8099-11ea-86f7-92aebbc841d7.png)

**Comment by rootelement** [comment]
Are you saying that you'd shut off any fields in the forums preferences related to the account itself, but leave the notification preferences? I think that'd be fine. Can we add something above the forum preferences that says "View / Edit my Topcoder Profile" that links over to the profile page? I think what you're suggesting is fine though.

Ultimately, I'd prefer to have everything under the Topcoder profile, so I'm hoping in the future we can use the Vanilla API to surface those settings in the Topcoder Profile editor so everything's in one place.

**Comment by jmgasper** [comment]
Yeah, I'm thinking we shut off the Vanilla-specific stuff other than the notification preferences.  I think it'd be easy enough to expose some of this via some REST API call and integrate them in... somewhere?  Member API?
